on:
  push:
    tags:
      - '[1-9]+.[0-9]+.[0-9]+'

jobs:
  get_tag:
    name: Get tag name
    outputs:
      tag: ${{ steps.get_tag.outputs.tag }}
    runs-on: ubuntu-latest
    steps:
      - name: Get the tag name
        id: get_tag
        env:
          OPENGROK_REF: ${{ github.ref }}
        run: echo "::set-output name=tag::${OPENGROK_REF#\"refs/tags/\"}"
  build:
    runs-on: ubuntu-latest
    needs: get_tag
    steps:
    - name: Print tag
      env:
        ARG1: ${{needs.get_tag.outputs.tag}}
      run: ./dev/run.sh
