on:
  push:
    tags:
      - '[1-9]+.[0-9]+.[0-9]+'

jobs:
  get_tag:
    name: Get tag name
    outputs:
      tag: ${{ steps.get_tag.outputs.tag }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master branch
        uses: actions/checkout@v2
      - name: Get the tag name
        id: get_tag
        env:
          OPENGROK_REF: ${{ github.ref }}
        run: ./dev/ref2tag.sh
  build:
    runs-on: ubuntu-latest
    needs: get_tag
    steps:
    - name: Checkout master branch
      uses: actions/checkout@v2
    - name: Print tag
      env:
        ARG1: ${{needs.get_tag.outputs.tag}}
      run: ./dev/run.sh
